services:
  - type: web
    name: kejamarket
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.cwqmtrwdbjmsrrqjkfmj:Stallonjevugwe4@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        value: 821b62dccd1d6a0c4d8262002c9ed1c5d1e8d0e0aa6ea0e63d15bfaaf3886b4191321f40d4c10fb076c93ddd58e7d93b04b42e68086ff5321b7bfc0b987d3ff4
      - key: AT_USERNAME
        value: kejamarket
      - key: AT_API_KEY
        value: atsk_bdabf24586133b346f31f648972e20184f64dc60e215e175c948b83d5e5e720bf9991634
      - key: MPESA_CONSUMER_KEY
        value: YOUR_CONSUMER_KEY_HERE
      - key: MPESA_CONSUMER_SECRET
        value: YOUR_CONSUMER_SECRET_HERE
      - key: MPESA_PASSKEY
        value: YOUR_PASSKEY_HERE
      - key: MPESA_PAYBILL
        value: "303030"
      - key: MPESA_ACCOUNT
        value: "2057103992"
      - key: MPESA_ENV
        value: sandbox
      - key: MPESA_CALLBACK_URL
        sync: false
    autoDeploy: true